
def func():
 print('indent')
   print('indent')
    print('indent')
      print('indent')
        print('indent')
          print('indent')
            print('indent')
              print('indent')
                print('indent')
                  print('indent')
                    print('indent')
                      print('indent')
                         print('indent')
print('dedent')
